// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AssistantEventsApiV1AssistantRunsRunIdEventsGetData, AssistantEventsApiV1AssistantRunsRunIdEventsGetErrors, AssistantEventsApiV1AssistantRunsRunIdEventsGetResponses, AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostData, AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostErrors, AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostResponses, AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostData, AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostErrors, AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostResponses, AssistantRunApiV1AssistantRunsRunIdGetData, AssistantRunApiV1AssistantRunsRunIdGetErrors, AssistantRunApiV1AssistantRunsRunIdGetResponses, AuditApiV1AuditsAuditIdGetData, AuditApiV1AuditsAuditIdGetErrors, AuditApiV1AuditsAuditIdGetResponses, CatalogApiV1CatalogGetData, CatalogApiV1CatalogGetResponses, CreateAssistantSessionApiV1AssistantSessionsPostData, CreateAssistantSessionApiV1AssistantSessionsPostResponses, ForecastApiV1ForecastsDesignatedDayPostData, ForecastApiV1ForecastsDesignatedDayPostErrors, ForecastApiV1ForecastsDesignatedDayPostResponses, HealthHealthGetData, HealthHealthGetResponses, QueryApiV1QueriesPostData, QueryApiV1QueriesPostErrors, QueryApiV1QueriesPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Assistant Run
 */
export const assistantRunApiV1AssistantRunsRunIdGet = <ThrowOnError extends boolean = false>(options: Options<AssistantRunApiV1AssistantRunsRunIdGetData, ThrowOnError>): RequestResult<AssistantRunApiV1AssistantRunsRunIdGetResponses, AssistantRunApiV1AssistantRunsRunIdGetErrors, ThrowOnError> => (options.client ?? client).get<AssistantRunApiV1AssistantRunsRunIdGetResponses, AssistantRunApiV1AssistantRunsRunIdGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/assistant/runs/{run_id}',
    ...options
});

/**
 * Assistant Events
 */
export const assistantEventsApiV1AssistantRunsRunIdEventsGet = <ThrowOnError extends boolean = false>(options: Options<AssistantEventsApiV1AssistantRunsRunIdEventsGetData, ThrowOnError>): RequestResult<AssistantEventsApiV1AssistantRunsRunIdEventsGetResponses, AssistantEventsApiV1AssistantRunsRunIdEventsGetErrors, ThrowOnError> => (options.client ?? client).get<AssistantEventsApiV1AssistantRunsRunIdEventsGetResponses, AssistantEventsApiV1AssistantRunsRunIdEventsGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/assistant/runs/{run_id}/events',
    ...options
});

/**
 * Assistant Feedback
 */
export const assistantFeedbackApiV1AssistantRunsRunIdFeedbackPost = <ThrowOnError extends boolean = false>(options: Options<AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostData, ThrowOnError>): RequestResult<AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostResponses, AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostErrors, ThrowOnError> => (options.client ?? client).post<AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostResponses, AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/assistant/runs/{run_id}/feedback',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create Assistant Session
 */
export const createAssistantSessionApiV1AssistantSessionsPost = <ThrowOnError extends boolean = false>(options?: Options<CreateAssistantSessionApiV1AssistantSessionsPostData, ThrowOnError>): RequestResult<CreateAssistantSessionApiV1AssistantSessionsPostResponses, unknown, ThrowOnError> => (options?.client ?? client).post<CreateAssistantSessionApiV1AssistantSessionsPostResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/assistant/sessions',
    ...options
});

/**
 * Assistant Message
 */
export const assistantMessageApiV1AssistantSessionsSessionIdMessagesPost = <ThrowOnError extends boolean = false>(options: Options<AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostData, ThrowOnError>): RequestResult<AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostResponses, AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostErrors, ThrowOnError> => (options.client ?? client).post<AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostResponses, AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/assistant/sessions/{session_id}/messages',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Audit
 */
export const auditApiV1AuditsAuditIdGet = <ThrowOnError extends boolean = false>(options: Options<AuditApiV1AuditsAuditIdGetData, ThrowOnError>): RequestResult<AuditApiV1AuditsAuditIdGetResponses, AuditApiV1AuditsAuditIdGetErrors, ThrowOnError> => (options.client ?? client).get<AuditApiV1AuditsAuditIdGetResponses, AuditApiV1AuditsAuditIdGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/audits/{audit_id}',
    ...options
});

/**
 * Catalog
 */
export const catalogApiV1CatalogGet = <ThrowOnError extends boolean = false>(options?: Options<CatalogApiV1CatalogGetData, ThrowOnError>): RequestResult<CatalogApiV1CatalogGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<CatalogApiV1CatalogGetResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/catalog',
    ...options
});

/**
 * Forecast
 */
export const forecastApiV1ForecastsDesignatedDayPost = <ThrowOnError extends boolean = false>(options: Options<ForecastApiV1ForecastsDesignatedDayPostData, ThrowOnError>): RequestResult<ForecastApiV1ForecastsDesignatedDayPostResponses, ForecastApiV1ForecastsDesignatedDayPostErrors, ThrowOnError> => (options.client ?? client).post<ForecastApiV1ForecastsDesignatedDayPostResponses, ForecastApiV1ForecastsDesignatedDayPostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/forecasts/designated-day',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Query
 */
export const queryApiV1QueriesPost = <ThrowOnError extends boolean = false>(options: Options<QueryApiV1QueriesPostData, ThrowOnError>): RequestResult<QueryApiV1QueriesPostResponses, QueryApiV1QueriesPostErrors, ThrowOnError> => (options.client ?? client).post<QueryApiV1QueriesPostResponses, QueryApiV1QueriesPostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/queries',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>): RequestResult<HealthHealthGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });
