// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AssistantArchitectureStage
 */
export type AssistantArchitectureStage = {
    /**
     * Detail
     */
    detail: string;
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Owner
     */
    owner: 'llm' | 'deterministic' | 'human';
};

/**
 * AssistantCapabilities
 */
export type AssistantCapabilities = {
    active_runtime: ModelRuntime;
    /**
     * Architecture
     */
    architecture: Array<AssistantArchitectureStage>;
    /**
     * Capability Registry Version
     */
    capability_registry_version: string;
    /**
     * Data Scope
     */
    data_scope: 'synthetic' | 'production-shadow' | 'production-readonly';
    /**
     * Deterministic Controls
     */
    deterministic_controls: Array<string>;
    /**
     * Implementation Status
     */
    implementation_status: 'local_governed_prototype';
    /**
     * Model Responsibilities
     */
    model_responsibilities: Array<string>;
    /**
     * Operation Capabilities
     */
    operation_capabilities?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Production Gaps
     */
    production_gaps: Array<string>;
    /**
     * Prohibited Model Actions
     */
    prohibited_model_actions: Array<string>;
    /**
     * Validated Milestones
     */
    validated_milestones: Array<ValidationMilestone>;
};

/**
 * AssistantMessageRequest
 */
export type AssistantMessageRequest = {
    /**
     * Message
     */
    message: string;
};

/**
 * AssistantResponse
 */
export type AssistantResponse = {
    /**
     * Answer
     */
    answer: string;
    /**
     * Assumptions
     */
    assumptions?: Array<string>;
    /**
     * Charts
     */
    charts?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Evidence Refs
     */
    evidence_refs?: Array<string>;
    /**
     * Follow Up Questions
     */
    follow_up_questions?: Array<string>;
    /**
     * Key Findings
     */
    key_findings?: Array<string>;
    /**
     * Limitations
     */
    limitations?: Array<string>;
    /**
     * Recommendations
     */
    recommendations?: Array<string>;
};

/**
 * AuditSummary
 */
export type AuditSummary = {
    /**
     * Audit Id
     */
    audit_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Data Source
     */
    data_source: string;
    /**
     * Operation
     */
    operation: string;
    /**
     * Query Fingerprint
     */
    query_fingerprint: string;
    /**
     * Row Count
     */
    row_count: number;
    /**
     * Status
     */
    status: string;
};

/**
 * CapabilityMatch
 */
export type CapabilityMatch = {
    /**
     * Answer Policy
     */
    answer_policy: 'deterministic_table' | 'deterministic_summary' | 'llm_synthesis' | 'llm_general' | 'llm_hybrid';
    /**
     * Capability Id
     */
    capability_id?: string | null;
    /**
     * Completeness Policy
     */
    completeness_policy?: 'require_complete' | 'reject_if_truncated';
    /**
     * Missing Slots
     */
    missing_slots?: Array<string>;
    /**
     * Registry Version
     */
    registry_version: string;
    /**
     * Status
     */
    status: 'matched' | 'missing_slots' | 'unavailable';
    /**
     * Tools
     */
    tools?: Array<string>;
    /**
     * Unavailable Tools
     */
    unavailable_tools?: Array<string>;
};

/**
 * CatalogOption
 */
export type CatalogOption = {
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
};

/**
 * CatalogResponse
 */
export type CatalogResponse = {
    /**
     * Access Policy
     */
    access_policy?: string | null;
    /**
     * Available Dates
     */
    available_dates: Array<string>;
    /**
     * City
     */
    city?: string | null;
    /**
     * Data Scope
     */
    data_scope: 'synthetic' | 'production-shadow' | 'production-readonly';
    default_time_range: TimeRange;
    /**
     * Dimensions
     */
    dimensions: Array<CatalogOption>;
    /**
     * Directions
     */
    directions: Array<CatalogOption>;
    /**
     * Freshness Status
     */
    freshness_status?: 'fresh' | 'stale' | 'unknown' | 'not_applicable';
    /**
     * Lines
     */
    lines: Array<string>;
    /**
     * Logical Registry Hash
     */
    logical_registry_hash?: string | null;
    /**
     * Logical Registry Version
     */
    logical_registry_version?: string | null;
    /**
     * Metrics
     */
    metrics: Array<MetricCatalogItem>;
    /**
     * Physical Mapping Hash
     */
    physical_mapping_hash?: string | null;
    /**
     * Physical Mapping Version
     */
    physical_mapping_version?: string | null;
    /**
     * Quality Gate
     */
    quality_gate?: string | null;
    /**
     * Quality Gate Evaluated At
     */
    quality_gate_evaluated_at?: string | null;
    /**
     * Quality Status
     */
    quality_status?: 'pass' | 'warning' | 'blocked' | 'unknown';
    /**
     * Registration Quality Status
     */
    registration_quality_status?: 'pass' | 'warning' | 'blocked' | 'unknown';
    /**
     * Registration Status
     */
    registration_status?: 'approved' | 'candidate' | 'blocked' | 'unknown';
    /**
     * Runtime Quality Status
     */
    runtime_quality_status?: 'pass' | 'warning' | 'blocked' | 'unknown';
    /**
     * Source Version
     */
    source_version?: string | null;
    /**
     * Stations
     */
    stations: Array<string>;
    /**
     * Timezone
     */
    timezone: 'Asia/Shanghai';
};

/**
 * ComparisonPeriods
 */
export type ComparisonPeriods = {
    baseline: TimeRange;
    comparison: TimeRange;
    /**
     * Relation
     */
    relation?: 'explicit' | 'previous_period' | 'year_over_year';
};

/**
 * CoverageEvidence
 */
export type CoverageEvidence = {
    /**
     * Authoritative Master
     */
    authoritative_master?: boolean;
    /**
     * City
     */
    city?: string | null;
    /**
     * Complete
     */
    complete?: boolean;
    /**
     * Coverage Type
     */
    coverage_type?: 'unknown' | 'observed_window' | 'registered_catalog' | 'query_result' | 'derived_result' | 'capability_readiness' | 'external_navigation' | 'general_context';
    /**
     * Dataset Role
     */
    dataset_role?: 'actual' | 'reference' | 'forecast' | null;
    /**
     * Freshness Status
     */
    freshness_status?: string | null;
    /**
     * Matched Count
     */
    matched_count?: number | null;
    /**
     * Returned Count
     */
    returned_count?: number;
    /**
     * Scope Label
     */
    scope_label?: string;
    /**
     * Source Version
     */
    source_version?: string | null;
    /**
     * Time Range
     */
    time_range?: {
        [key: string]: string;
    };
    /**
     * Truncated
     */
    truncated?: boolean;
};

/**
 * DatasetEligibility
 */
export type DatasetEligibility = {
    /**
     * Eligible
     */
    eligible?: boolean;
    /**
     * Reasons
     */
    reasons?: Array<string>;
    /**
     * Requires Human Confirmation
     */
    requires_human_confirmation?: boolean;
};

/**
 * EntityCandidate
 */
export type EntityCandidate = {
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Source
     */
    source: 'registered_catalog' | 'observed_database_entity';
    /**
     * Type
     */
    type: 'line' | 'station';
};

/**
 * EntityResolution
 */
export type EntityResolution = {
    /**
     * Candidates
     */
    candidates?: Array<EntityCandidate>;
    /**
     * Raw Text
     */
    raw_text: string;
    /**
     * Reference
     */
    reference?: 'named' | 'collection' | 'deictic';
    /**
     * Role
     */
    role?: 'subject' | 'origin' | 'destination' | 'context';
    /**
     * Selected Id
     */
    selected_id?: string | null;
    /**
     * Selected Name
     */
    selected_name?: string | null;
    /**
     * Status
     */
    status: 'resolved' | 'ambiguous' | 'not_found' | 'not_applicable';
    /**
     * Type
     */
    type: 'line' | 'station' | 'place' | 'event' | 'unknown';
};

/**
 * EntitySet
 */
export type EntitySet = {
    /**
     * Directions
     */
    directions?: Array<string>;
    /**
     * Groups
     */
    groups?: Array<string>;
    /**
     * Lines
     */
    lines?: Array<string>;
    /**
     * Regions
     */
    regions?: Array<string>;
    /**
     * Stations
     */
    stations?: Array<string>;
};

/**
 * EventSpec
 */
export type EventSpec = {
    /**
     * Attendance
     */
    attendance?: number;
    /**
     * Event Name
     */
    event_name?: string;
    /**
     * Impacted Stations
     */
    impacted_stations?: Array<string>;
    /**
     * Target Date
     */
    target_date?: string | null;
    /**
     * Venue
     */
    venue?: string | null;
};

/**
 * EvidenceItem
 */
export type EvidenceItem = {
    /**
     * Access Scope Hash
     */
    access_scope_hash?: string | null;
    /**
     * Block Reason
     */
    block_reason?: string | null;
    /**
     * Calculation Method
     */
    calculation_method?: string | null;
    /**
     * Claim
     */
    claim: string;
    /**
     * Complete
     */
    complete?: boolean;
    coverage?: CoverageEvidence;
    /**
     * Evidence Id
     */
    evidence_id: string;
    /**
     * Kind
     */
    kind: 'fact' | 'statistic' | 'chart' | 'model_output' | 'knowledge';
    /**
     * Logical Plan Hash
     */
    logical_plan_hash?: string | null;
    /**
     * Matched Count Unknown
     */
    matched_count_unknown?: boolean;
    /**
     * Matched Row Count
     */
    matched_row_count?: number | null;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    };
    /**
     * Policy Snapshot Id
     */
    policy_snapshot_id?: string | null;
    /**
     * Query Fingerprint
     */
    query_fingerprint?: string | null;
    /**
     * Result Hash
     */
    result_hash?: string | null;
    /**
     * Result Schema
     */
    result_schema?: Array<ResultFieldSpec>;
    /**
     * Returned Row Count
     */
    returned_row_count?: number;
    /**
     * Source Evidence Ids
     */
    source_evidence_ids?: Array<string>;
    /**
     * Step Id
     */
    step_id: string;
    /**
     * Structured Claims
     */
    structured_claims?: Array<StructuredClaim>;
    /**
     * Truncated
     */
    truncated?: boolean;
    /**
     * Value
     */
    value?: unknown;
    /**
     * Warnings
     */
    warnings?: Array<string>;
};

/**
 * EvidencePacket
 */
export type EvidencePacket = {
    /**
     * Charts
     */
    charts?: Array<EvidenceItem>;
    /**
     * Conflicts
     */
    conflicts?: Array<string>;
    /**
     * Facts
     */
    facts?: Array<EvidenceItem>;
    /**
     * Knowledge Sources
     */
    knowledge_sources?: Array<EvidenceItem>;
    /**
     * Missing Evidence
     */
    missing_evidence?: Array<string>;
    /**
     * Model Outputs
     */
    model_outputs?: Array<EvidenceItem>;
    /**
     * Question
     */
    question: string;
    /**
     * Schema Version
     */
    schema_version?: '2.0';
    /**
     * Statistics
     */
    statistics?: Array<EvidenceItem>;
};

/**
 * ForecastRequest
 */
export type ForecastRequest = {
    /**
     * Limit
     */
    limit?: number;
    /**
     * Reference Date
     */
    reference_date: string;
    /**
     * Scheme Id
     */
    scheme_id: number;
    /**
     * Target Date
     */
    target_date: string;
};

/**
 * ForecastResponse
 */
export type ForecastResponse = {
    audit: AuditSummary;
    /**
     * Method
     */
    method: 'reference_day_copy';
    /**
     * Reference Date
     */
    reference_date: string;
    /**
     * Row Count
     */
    row_count: number;
    /**
     * Rows
     */
    rows: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Scheme Id
     */
    scheme_id: number;
    /**
     * Status
     */
    status: 'answer';
    /**
     * Target Date
     */
    target_date: string;
};

/**
 * GovernanceAccessScope
 */
export type GovernanceAccessScope = {
    /**
     * Access Scope Hash
     */
    access_scope_hash: string;
    /**
     * Allowed Cities
     */
    allowed_cities: Array<string>;
    /**
     * Allowed Dataset Roles
     */
    allowed_dataset_roles: Array<'actual' | 'reference' | 'forecast'>;
    /**
     * Allowed Metrics
     */
    allowed_metrics: Array<string>;
    /**
     * Export Policy
     */
    export_policy: 'deny' | 'controlled';
    /**
     * Max Time Range Hours
     */
    max_time_range_hours: number;
    /**
     * Policy Snapshot Id
     */
    policy_snapshot_id: string;
    /**
     * Row Limit
     */
    row_limit: number;
};

/**
 * GovernanceDataSource
 */
export type GovernanceDataSource = {
    /**
     * Access Policy
     */
    access_policy?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * Freshness Status
     */
    freshness_status: 'fresh' | 'stale' | 'unknown' | 'not_applicable';
    /**
     * Logical Registry Hash
     */
    logical_registry_hash?: string | null;
    /**
     * Logical Registry Version
     */
    logical_registry_version?: string | null;
    /**
     * Physical Mapping Hash
     */
    physical_mapping_hash?: string | null;
    /**
     * Physical Mapping Version
     */
    physical_mapping_version?: string | null;
    /**
     * Quality Gate
     */
    quality_gate?: string | null;
    /**
     * Quality Gate Evaluated At
     */
    quality_gate_evaluated_at?: string | null;
    /**
     * Quality Status
     */
    quality_status: 'pass' | 'warning' | 'blocked' | 'unknown';
    /**
     * Registration Quality Status
     */
    registration_quality_status: 'pass' | 'warning' | 'blocked' | 'unknown';
    /**
     * Registration Status
     */
    registration_status: 'approved' | 'candidate' | 'blocked' | 'unknown';
    /**
     * Runtime Quality Status
     */
    runtime_quality_status: 'pass' | 'warning' | 'blocked' | 'unknown';
    /**
     * Source Version
     */
    source_version?: string | null;
};

/**
 * GovernanceIdentity
 */
export type GovernanceIdentity = {
    /**
     * Identity Adapter
     */
    identity_adapter: 'static-token-single-subject';
    /**
     * Multi User Isolation
     */
    multi_user_isolation: boolean;
    /**
     * Roles
     */
    roles: Array<string>;
    /**
     * Subject Id
     */
    subject_id: string;
    /**
     * Tenant Or Department
     */
    tenant_or_department: string;
};

/**
 * GovernanceModelPolicy
 */
export type GovernanceModelPolicy = {
    /**
     * Active Model
     */
    active_model?: string | null;
    /**
     * Active Provider
     */
    active_provider: string;
    /**
     * Data Egress
     */
    data_egress: 'deny' | 'synthetic-only' | 'aggregate-approved';
    /**
     * Endpoint Binding Verified
     */
    endpoint_binding_verified: boolean;
    /**
     * Endpoint Policy Id
     */
    endpoint_policy_id: string;
    /**
     * Endpoint Target Hash
     */
    endpoint_target_hash: string;
    /**
     * Evidence Egress Allowed
     */
    evidence_egress_allowed: boolean;
    /**
     * Intent Egress
     */
    intent_egress: 'deny' | 'synthetic-only' | 'metadata-approved';
    /**
     * Intent Egress Allowed
     */
    intent_egress_allowed: boolean;
};

/**
 * GovernancePromotionGate
 */
export type GovernancePromotionGate = {
    /**
     * Blockers
     */
    blockers: Array<string>;
    /**
     * Configured Status
     */
    configured_status: string;
    /**
     * Enforced
     */
    enforced: boolean;
    /**
     * Gate Id
     */
    gate_id: string;
    /**
     * Local Live Shadow Acknowledged
     */
    local_live_shadow_acknowledged: boolean;
    /**
     * Missing Owner Roles
     */
    missing_owner_roles: Array<string>;
    /**
     * Missing Thresholds
     */
    missing_thresholds: Array<string>;
    /**
     * Pending Artifacts
     */
    pending_artifacts: Array<string>;
    /**
     * Ready
     */
    ready: boolean;
    /**
     * Runtime Flag Requested
     */
    runtime_flag_requested: boolean;
};

/**
 * GovernanceStatus
 */
export type GovernanceStatus = {
    access_scope: GovernanceAccessScope;
    /**
     * Assistant Enabled
     */
    assistant_enabled: boolean;
    /**
     * Assistant Status
     */
    assistant_status: 'synthetic_baseline' | 'disabled_by_runtime_flag' | 'blocked_by_promotion_gate' | 'enabled_for_local_shadow' | 'enabled_after_promotion';
    /**
     * Data Scope
     */
    data_scope: 'synthetic' | 'production-shadow' | 'production-readonly';
    data_source: GovernanceDataSource;
    identity: GovernanceIdentity;
    model_policy: GovernanceModelPolicy;
    promotion: GovernancePromotionGate;
    tool_registry: GovernanceToolRegistry;
};

/**
 * GovernanceToolRegistry
 */
export type GovernanceToolRegistry = {
    /**
     * Registered Tools
     */
    registered_tools: Array<string>;
    /**
     * Tool Count
     */
    tool_count: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Data Scope
     */
    data_scope: 'synthetic' | 'production-shadow' | 'production-readonly';
    /**
     * Data Status
     */
    data_status?: 'synthetic-ready' | 'shadow-configured';
    /**
     * Environment
     */
    environment: string;
    /**
     * Service
     */
    service: string;
    /**
     * Status
     */
    status: 'ok';
    /**
     * Version
     */
    version: string;
};

/**
 * HumanFeedback
 */
export type HumanFeedback = {
    /**
     * Accepted
     */
    accepted?: boolean | null;
    /**
     * Correction
     */
    correction: string;
    /**
     * Recorded At
     */
    recorded_at?: string;
};

/**
 * HumanFeedbackRequest
 */
export type HumanFeedbackRequest = {
    /**
     * Accepted
     */
    accepted: boolean;
    adopted_response?: AssistantResponse | null;
    /**
     * Correction
     */
    correction: string;
};

/**
 * IntentEnvelope
 */
export type IntentEnvelope = {
    /**
     * Ambiguities
     */
    ambiguities?: Array<string>;
    /**
     * City
     */
    city?: string | null;
    /**
     * Dataset Role
     */
    dataset_role?: 'actual' | 'reference' | 'forecast';
    entities?: EntitySet;
    event_spec?: EventSpec | null;
    /**
     * Metric Version
     */
    metric_version?: string;
    /**
     * Metrics
     */
    metrics?: Array<string>;
    /**
     * Needs Clarification
     */
    needs_clarification?: boolean;
    /**
     * Source Version
     */
    source_version?: string | null;
    /**
     * Task Type
     */
    task_type: 'query' | 'compare' | 'forecast' | 'alert' | 'transfer' | 'geo' | 'correlation' | 'diagnosis' | 'trend' | 'report' | 'travel' | 'help' | 'general' | 'external';
    /**
     * Time Grain
     */
    time_grain?: 'source' | '10m' | '15m' | '30m' | 'hour' | 'day';
    /**
     * Time Scope
     */
    time_scope?: {
        [key: string]: unknown;
    };
    transfer_spec?: TransferAnalysisSpec | null;
    travel_spec?: TravelPlanSpec | null;
    /**
     * User Goal
     */
    user_goal: string;
};

/**
 * MetricCatalogItem
 */
export type MetricCatalogItem = {
    /**
     * Admission Status
     */
    admission_status?: 'approved' | 'candidate' | 'synthetic_only' | 'blocked';
    /**
     * Allowed Grains
     */
    allowed_grains?: Array<string>;
    /**
     * Dataset Role
     */
    dataset_role?: 'actual' | 'reference' | 'forecast';
    /**
     * Definition
     */
    definition?: string;
    /**
     * Dimensions
     */
    dimensions: Array<string>;
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Logical Dataset
     */
    logical_dataset?: string;
    /**
     * Unit
     */
    unit: string;
    /**
     * Version
     */
    version?: string;
};

/**
 * MetricResolution
 */
export type MetricResolution = {
    /**
     * Candidates
     */
    candidates?: Array<string>;
    /**
     * Raw Text
     */
    raw_text: string;
    /**
     * Selected Metric
     */
    selected_metric?: string | null;
    /**
     * Status
     */
    status: 'resolved' | 'ambiguous' | 'not_found' | 'defaulted';
};

/**
 * ModelEgressRecord
 */
export type ModelEgressRecord = {
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Completed At
     */
    completed_at?: string | null;
    /**
     * Decision
     */
    decision: 'denied' | 'approved';
    /**
     * Endpoint Binding Verified
     */
    endpoint_binding_verified: boolean;
    /**
     * Endpoint Policy Id
     */
    endpoint_policy_id: string;
    /**
     * Endpoint Target Hash
     */
    endpoint_target_hash: string;
    /**
     * Exact Payload Hash
     */
    exact_payload_hash: string;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Outbound Field Paths
     */
    outbound_field_paths?: Array<string>;
    /**
     * Provider
     */
    provider: string;
    /**
     * Purpose
     */
    purpose: 'semantic_compile' | 'intent_candidate' | 'synthesis';
    /**
     * Started At
     */
    started_at: string;
    /**
     * Status
     */
    status: 'started' | 'succeeded' | 'failed' | 'not_called';
};

/**
 * ModelRuntime
 */
export type ModelRuntime = {
    /**
     * Elapsed Seconds
     */
    elapsed_seconds?: number | null;
    /**
     * Execution Role
     */
    execution_role?: 'deterministic_active' | 'model_active' | 'shadow_report_only';
    /**
     * Input Tokens
     */
    input_tokens?: number | null;
    /**
     * Invocation Status
     */
    invocation_status?: 'not_applicable' | 'configured' | 'succeeded' | 'failed' | 'partial';
    /**
     * Mode
     */
    mode?: 'offline_deterministic' | 'local_governed_model' | 'openai_compatible';
    /**
     * Model
     */
    model?: string | null;
    /**
     * Model Calls
     */
    model_calls?: number;
    /**
     * Output Tokens
     */
    output_tokens?: number | null;
    /**
     * Provider
     */
    provider?: string;
    /**
     * Provider Calls
     */
    provider_calls?: number;
    /**
     * Real Model Active
     */
    real_model_active?: boolean;
    /**
     * Real Model Configured
     */
    real_model_configured?: boolean;
    /**
     * Reasoning Tokens
     */
    reasoning_tokens?: number | null;
    /**
     * Total Tokens
     */
    total_tokens?: number | null;
    /**
     * Usage Reporting
     */
    usage_reporting?: 'not_applicable' | 'unavailable' | 'partial' | 'complete';
};

/**
 * OperationIR
 */
export type OperationIr = {
    /**
     * Answer Policy
     */
    answer_policy?: 'deterministic_table' | 'deterministic_summary' | 'llm_synthesis' | 'llm_general' | 'llm_hybrid';
    /**
     * Completeness Required
     */
    completeness_required?: boolean;
    /**
     * Departure Time
     */
    departure_time?: string | null;
    /**
     * Destination
     */
    destination?: string | null;
    /**
     * Entity Type
     */
    entity_type?: 'station' | 'line' | 'direction' | 'date' | 'metric' | null;
    /**
     * Filters
     */
    filters?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Metric
     */
    metric?: string | null;
    /**
     * Operation
     */
    operation: 'list_entities' | 'describe_entity' | 'list_metrics' | 'list_available_dates' | 'summarize_dataset' | 'query_metric' | 'rank_entities' | 'compare_periods' | 'forecast' | 'alert' | 'transfer' | 'geo' | 'correlation' | 'diagnosis' | 'trend_analysis' | 'report' | 'capability_readiness' | 'travel_plan' | 'capability_help' | 'general_answer' | 'external_answer';
    /**
     * Origin
     */
    origin?: string | null;
    /**
     * Route Confidence
     */
    route_confidence?: 'high' | 'model_candidate';
    /**
     * Schema Version
     */
    schema_version?: '1.0';
    /**
     * Scope
     */
    scope?: 'approved_observation_window' | 'registered_catalog' | 'authoritative_master' | 'requested_query_scope' | 'external_navigation' | 'general_knowledge';
    /**
     * Target Query
     */
    target_query?: string | null;
    /**
     * Time Range
     */
    time_range?: {
        [key: string]: string;
    };
    /**
     * Travel Mode
     */
    travel_mode?: 'public_transit' | 'driving' | 'walking' | null;
};

/**
 * QueryFilter
 */
export type QueryFilter = {
    /**
     * Field
     */
    field: 'line_id' | 'station_id' | 'direction';
    /**
     * Operator
     */
    operator: 'eq' | 'in';
    /**
     * Value
     */
    value: string | Array<string>;
};

/**
 * QueryOrder
 */
export type QueryOrder = {
    /**
     * Direction
     */
    direction?: 'asc' | 'desc';
    /**
     * Field
     */
    field: string;
};

/**
 * QueryRequest
 */
export type QueryRequest = {
    /**
     * Calendar Version
     */
    calendar_version?: string | null;
    /**
     * City
     */
    city?: string | null;
    comparison_periods?: ComparisonPeriods | null;
    /**
     * Cross Midnight Policy
     */
    cross_midnight_policy?: 'reject' | 'service_day_calendar';
    /**
     * Data As Of
     */
    data_as_of?: string | null;
    /**
     * Dataset Role
     */
    dataset_role?: 'actual' | 'reference' | 'forecast';
    /**
     * Dimensions
     */
    dimensions: Array<'line' | 'station' | 'direction' | 'time'>;
    /**
     * Filters
     */
    filters: Array<QueryFilter>;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Metric
     */
    metric: string;
    /**
     * Metric Version
     */
    metric_version?: string;
    /**
     * Order By
     */
    order_by?: Array<QueryOrder>;
    /**
     * Service Day
     */
    service_day?: string | null;
    /**
     * Source Version
     */
    source_version?: string | null;
    /**
     * Time Basis
     */
    time_basis?: 'event_time' | 'service_day';
    /**
     * Time Grain
     */
    time_grain?: 'source' | '10m' | '15m' | '30m' | 'hour' | 'day';
    time_range: TimeRange;
    /**
     * Timezone
     */
    timezone?: 'Asia/Shanghai';
};

/**
 * QueryResponse
 */
export type QueryResponse = {
    audit: AuditSummary;
    /**
     * Data Scope
     */
    data_scope?: 'synthetic' | 'production-shadow' | 'production-readonly';
    /**
     * Dimensions
     */
    dimensions: Array<string>;
    /**
     * Metric
     */
    metric: string;
    /**
     * Provenance
     */
    provenance?: {
        [key: string]: unknown;
    };
    /**
     * Row Count
     */
    row_count: number;
    /**
     * Rows
     */
    rows: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Status
     */
    status: 'answer';
};

/**
 * ResultFieldSpec
 */
export type ResultFieldSpec = {
    /**
     * Field
     */
    field: string;
    /**
     * Type
     */
    type: 'boolean' | 'integer' | 'number' | 'null' | 'string';
};

/**
 * RunRecord
 */
export type RunRecord = {
    /**
     * Access Scope Hash
     */
    access_scope_hash: string;
    adopted_response?: AssistantResponse | null;
    capability_match?: CapabilityMatch | null;
    /**
     * Created At
     */
    created_at?: string;
    dataset_eligibility?: DatasetEligibility;
    /**
     * Entity Resolutions
     */
    entity_resolutions?: Array<EntityResolution>;
    /**
     * Events
     */
    events?: Array<{
        [key: string]: unknown;
    }>;
    evidence?: EvidencePacket | null;
    /**
     * Failure Category
     */
    failure_category?: 'material_ambiguity' | 'intent_unrecognized' | 'entity_not_found' | 'capability_gap' | 'query_ir_unsupported' | 'data_unavailable' | 'result_truncated' | 'tool_failure' | 'model_failure' | 'verification_failure' | 'authorization_failure' | null;
    /**
     * Human Feedback
     */
    human_feedback?: Array<HumanFeedback>;
    intent?: IntentEnvelope | null;
    /**
     * Intent Route
     */
    intent_route?: 'deterministic' | 'model_candidate' | 'semantic_model' | 'semantic_fallback' | 'clarification';
    /**
     * Metric Resolutions
     */
    metric_resolutions?: Array<MetricResolution>;
    /**
     * Model Egress
     */
    model_egress?: Array<ModelEgressRecord>;
    model_runtime?: ModelRuntime;
    operation_ir?: OperationIr | null;
    /**
     * Original Question
     */
    original_question: string;
    /**
     * Owner Subject Id
     */
    owner_subject_id: string;
    /**
     * Owner Tenant Or Department
     */
    owner_tenant_or_department: string;
    plan?: TaskPlan | null;
    /**
     * Planner Route
     */
    planner_route?: 'deterministic';
    /**
     * Policy Snapshot Id
     */
    policy_snapshot_id: string;
    /**
     * Provider
     */
    provider: string;
    /**
     * Replans
     */
    replans?: Array<TaskPlan>;
    response?: AssistantResponse | null;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Selected Context
     */
    selected_context?: {
        [key: string]: unknown;
    };
    /**
     * Semantic Disagreements
     */
    semantic_disagreements?: Array<string>;
    semantic_frame?: SemanticFrame | null;
    semantic_memory_snapshot?: SemanticMemory;
    semantic_shadow_frame?: SemanticFrame | null;
    /**
     * Semantic Source
     */
    semantic_source?: 'model' | 'deterministic_fallback' | null;
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Status
     */
    status?: 'running' | 'completed' | 'needs_clarification' | 'failed';
    /**
     * Tool Results
     */
    tool_results?: Array<ToolResult>;
    verification?: VerificationReport | null;
};

/**
 * SemanticEntityMention
 *
 * A user-language entity mention; database identifiers are deliberately absent.
 */
export type SemanticEntityMention = {
    /**
     * Raw Text
     */
    raw_text: string;
    /**
     * Reference
     */
    reference?: 'named' | 'collection' | 'deictic';
    /**
     * Role
     */
    role?: 'subject' | 'origin' | 'destination' | 'context';
    /**
     * Type
     */
    type: 'line' | 'station' | 'place' | 'event' | 'unknown';
};

/**
 * SemanticFrame
 *
 * Open-language meaning compiled by GPT; it cannot contain SQL or physical IDs.
 */
export type SemanticFrame = {
    /**
     * Assumptions
     */
    assumptions?: Array<string>;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Defaults Allowed
     */
    defaults_allowed?: boolean;
    /**
     * Entity Mentions
     */
    entity_mentions?: Array<SemanticEntityMention>;
    /**
     * Evidence Requirements
     */
    evidence_requirements?: Array<'database_rows' | 'metric_definition' | 'general_knowledge' | 'external_live_data' | 'navigation'>;
    /**
     * Goal
     */
    goal: string;
    /**
     * Inherit Context
     */
    inherit_context?: boolean;
    /**
     * Material Missing Fields
     */
    material_missing_fields?: Array<string>;
    /**
     * Metric Mentions
     */
    metric_mentions?: Array<SemanticMetricMention>;
    /**
     * Operations
     */
    operations: Array<'discover' | 'describe' | 'query' | 'aggregate' | 'rank' | 'compare' | 'forecast' | 'diagnose' | 'explain' | 'travel' | 'help' | 'alert' | 'transfer' | 'geo' | 'correlate' | 'trend' | 'report'>;
    /**
     * Route
     */
    route: 'data' | 'general' | 'hybrid' | 'external' | 'clarify';
    /**
     * Schema Version
     */
    schema_version?: '1.0';
    /**
     * Target Kind
     */
    target_kind?: 'line' | 'station' | 'metric' | 'date' | 'dataset' | 'capability' | 'place' | 'event' | 'unspecified';
    time_expression?: SemanticTimeExpression;
};

/**
 * SemanticMemory
 */
export type SemanticMemory = {
    /**
     * Current Entities
     */
    current_entities?: {
        [key: string]: Array<string>;
    };
    /**
     * Current Metric
     */
    current_metric?: string | null;
    /**
     * Current Time Range
     */
    current_time_range?: {
        [key: string]: string;
    };
    /**
     * Last Operations
     */
    last_operations?: Array<'discover' | 'describe' | 'query' | 'aggregate' | 'rank' | 'compare' | 'forecast' | 'diagnose' | 'explain' | 'travel' | 'help' | 'alert' | 'transfer' | 'geo' | 'correlate' | 'trend' | 'report'>;
    /**
     * Last Route
     */
    last_route?: 'data' | 'general' | 'hybrid' | 'external' | 'clarify' | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * SemanticMetricMention
 */
export type SemanticMetricMention = {
    /**
     * Candidate Metrics
     */
    candidate_metrics?: Array<string>;
    /**
     * Raw Text
     */
    raw_text: string;
    /**
     * Resolution
     */
    resolution?: 'exact' | 'candidate' | 'unspecified' | 'unresolved';
};

/**
 * SemanticTimeExpression
 */
export type SemanticTimeExpression = {
    /**
     * Raw Text
     */
    raw_text?: string | null;
    /**
     * Resolution
     */
    resolution?: 'explicit' | 'default_allowed' | 'unspecified' | 'unresolved';
};

/**
 * SessionRecord
 */
export type SessionRecord = {
    /**
     * Access Scope Hash
     */
    access_scope_hash: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Messages
     */
    messages?: Array<{
        [key: string]: string;
    }>;
    /**
     * Owner Subject Id
     */
    owner_subject_id: string;
    /**
     * Owner Tenant Or Department
     */
    owner_tenant_or_department: string;
    /**
     * Policy Snapshot Id
     */
    policy_snapshot_id: string;
    semantic_memory?: SemanticMemory;
    /**
     * Session Id
     */
    session_id: string;
};

/**
 * StructuredClaim
 */
export type StructuredClaim = {
    /**
     * Aggregation
     */
    aggregation?: string | null;
    /**
     * Claim Type
     */
    claim_type: 'metric_total' | 'result_row';
    /**
     * Dimensions
     */
    dimensions?: {
        [key: string]: unknown;
    };
    /**
     * Metric Id
     */
    metric_id?: string | null;
    /**
     * Metric Version
     */
    metric_version?: string | null;
    /**
     * Unit
     */
    unit?: string | null;
    /**
     * Value
     */
    value?: number | number | null;
    /**
     * Values
     */
    values?: {
        [key: string]: number | number;
    };
};

/**
 * TaskPlan
 */
export type TaskPlan = {
    /**
     * Answer Format
     */
    answer_format?: string;
    /**
     * Expected Evidence
     */
    expected_evidence?: Array<string>;
    /**
     * Plan Id
     */
    plan_id: string;
    /**
     * Steps
     */
    steps: Array<ToolStep>;
    /**
     * Task Type
     */
    task_type: 'query' | 'compare' | 'forecast' | 'alert' | 'transfer' | 'geo' | 'correlation' | 'diagnosis' | 'trend' | 'report' | 'travel' | 'help' | 'general' | 'external';
};

/**
 * TimeRange
 */
export type TimeRange = {
    /**
     * End
     */
    end: string;
    /**
     * Start
     */
    start: string;
};

/**
 * ToolResult
 */
export type ToolResult = {
    /**
     * Access Scope Hash
     */
    access_scope_hash?: string | null;
    /**
     * Artifact Refs
     */
    artifact_refs?: Array<string>;
    /**
     * Block Reason
     */
    block_reason?: string | null;
    /**
     * Calculation Method
     */
    calculation_method?: string | null;
    /**
     * Complete
     */
    complete?: boolean;
    coverage?: CoverageEvidence;
    /**
     * Error Code
     */
    error_code?: string | null;
    /**
     * Logical Plan Hash
     */
    logical_plan_hash?: string | null;
    /**
     * Matched Count Unknown
     */
    matched_count_unknown?: boolean;
    /**
     * Matched Row Count
     */
    matched_row_count?: number | null;
    /**
     * Policy Snapshot Id
     */
    policy_snapshot_id?: string | null;
    /**
     * Query Fingerprint
     */
    query_fingerprint?: string | null;
    /**
     * Result Hash
     */
    result_hash?: string | null;
    /**
     * Returned Row Count
     */
    returned_row_count?: number;
    /**
     * Rows
     */
    rows?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Source Step Ids
     */
    source_step_ids?: Array<string>;
    /**
     * Status
     */
    status: 'success' | 'failed' | 'skipped';
    /**
     * Step Id
     */
    step_id: string;
    /**
     * Summary
     */
    summary?: {
        [key: string]: unknown;
    };
    /**
     * Tool
     */
    tool: string;
    /**
     * Truncated
     */
    truncated?: boolean;
    /**
     * Warnings
     */
    warnings?: Array<string>;
};

/**
 * ToolStep
 */
export type ToolStep = {
    /**
     * Arguments
     */
    arguments?: {
        [key: string]: unknown;
    };
    /**
     * Depends On
     */
    depends_on?: Array<string>;
    /**
     * Step Id
     */
    step_id: string;
    /**
     * Tool
     */
    tool: string;
};

/**
 * TransferAnalysisSpec
 */
export type TransferAnalysisSpec = {
    /**
     * Bus Scope
     */
    bus_scope?: Array<string>;
    /**
     * Output Dimensions
     */
    output_dimensions?: Array<string>;
    /**
     * Rail Scope
     */
    rail_scope?: Array<string>;
    /**
     * Window Minutes
     */
    window_minutes?: number;
};

/**
 * TravelPlanSpec
 */
export type TravelPlanSpec = {
    /**
     * City
     */
    city?: string | null;
    /**
     * Departure Time
     */
    departure_time?: string | null;
    /**
     * Destination
     */
    destination?: string | null;
    /**
     * Mode
     */
    mode?: 'public_transit' | 'driving' | 'walking';
    /**
     * Origin
     */
    origin?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * ValidationMilestone
 */
export type ValidationMilestone = {
    /**
     * Evidence
     */
    evidence: string;
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Scope
     */
    scope: string;
    /**
     * Status
     */
    status: 'verified' | 'partial' | 'not_started';
};

/**
 * VerificationReport
 */
export type VerificationReport = {
    /**
     * Errors
     */
    errors?: Array<string>;
    /**
     * Supported Evidence Refs
     */
    supported_evidence_refs?: Array<string>;
    /**
     * Valid
     */
    valid: boolean;
    /**
     * Warnings
     */
    warnings?: Array<string>;
};

export type AssistantCapabilitiesApiV1AssistantCapabilitiesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/assistant/capabilities';
};

export type AssistantCapabilitiesApiV1AssistantCapabilitiesGetResponses = {
    /**
     * Successful Response
     */
    200: AssistantCapabilities;
};

export type AssistantCapabilitiesApiV1AssistantCapabilitiesGetResponse = AssistantCapabilitiesApiV1AssistantCapabilitiesGetResponses[keyof AssistantCapabilitiesApiV1AssistantCapabilitiesGetResponses];

export type AssistantRunApiV1AssistantRunsRunIdGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/assistant/runs/{run_id}';
};

export type AssistantRunApiV1AssistantRunsRunIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssistantRunApiV1AssistantRunsRunIdGetError = AssistantRunApiV1AssistantRunsRunIdGetErrors[keyof AssistantRunApiV1AssistantRunsRunIdGetErrors];

export type AssistantRunApiV1AssistantRunsRunIdGetResponses = {
    /**
     * Successful Response
     */
    200: RunRecord;
};

export type AssistantRunApiV1AssistantRunsRunIdGetResponse = AssistantRunApiV1AssistantRunsRunIdGetResponses[keyof AssistantRunApiV1AssistantRunsRunIdGetResponses];

export type AssistantEventsApiV1AssistantRunsRunIdEventsGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/assistant/runs/{run_id}/events';
};

export type AssistantEventsApiV1AssistantRunsRunIdEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssistantEventsApiV1AssistantRunsRunIdEventsGetError = AssistantEventsApiV1AssistantRunsRunIdEventsGetErrors[keyof AssistantEventsApiV1AssistantRunsRunIdEventsGetErrors];

export type AssistantEventsApiV1AssistantRunsRunIdEventsGetResponses = {
    /**
     * Response Assistant Events Api V1 Assistant Runs  Run Id  Events Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type AssistantEventsApiV1AssistantRunsRunIdEventsGetResponse = AssistantEventsApiV1AssistantRunsRunIdEventsGetResponses[keyof AssistantEventsApiV1AssistantRunsRunIdEventsGetResponses];

export type AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostData = {
    body: HumanFeedbackRequest;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/assistant/runs/{run_id}/feedback';
};

export type AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostError = AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostErrors[keyof AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostErrors];

export type AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostResponses = {
    /**
     * Successful Response
     */
    200: RunRecord;
};

export type AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostResponse = AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostResponses[keyof AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostResponses];

export type CreateAssistantSessionApiV1AssistantSessionsPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/assistant/sessions';
};

export type CreateAssistantSessionApiV1AssistantSessionsPostResponses = {
    /**
     * Successful Response
     */
    200: SessionRecord;
};

export type CreateAssistantSessionApiV1AssistantSessionsPostResponse = CreateAssistantSessionApiV1AssistantSessionsPostResponses[keyof CreateAssistantSessionApiV1AssistantSessionsPostResponses];

export type AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostData = {
    body: AssistantMessageRequest;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/assistant/sessions/{session_id}/messages';
};

export type AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostError = AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostErrors[keyof AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostErrors];

export type AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostResponses = {
    /**
     * Successful Response
     */
    200: RunRecord;
};

export type AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostResponse = AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostResponses[keyof AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostResponses];

export type AuditApiV1AuditsAuditIdGetData = {
    body?: never;
    path: {
        /**
         * Audit Id
         */
        audit_id: string;
    };
    query?: never;
    url: '/api/v1/audits/{audit_id}';
};

export type AuditApiV1AuditsAuditIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuditApiV1AuditsAuditIdGetError = AuditApiV1AuditsAuditIdGetErrors[keyof AuditApiV1AuditsAuditIdGetErrors];

export type AuditApiV1AuditsAuditIdGetResponses = {
    /**
     * Successful Response
     */
    200: AuditSummary;
};

export type AuditApiV1AuditsAuditIdGetResponse = AuditApiV1AuditsAuditIdGetResponses[keyof AuditApiV1AuditsAuditIdGetResponses];

export type CatalogApiV1CatalogGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/catalog';
};

export type CatalogApiV1CatalogGetResponses = {
    /**
     * Successful Response
     */
    200: CatalogResponse;
};

export type CatalogApiV1CatalogGetResponse = CatalogApiV1CatalogGetResponses[keyof CatalogApiV1CatalogGetResponses];

export type ForecastApiV1ForecastsDesignatedDayPostData = {
    body: ForecastRequest;
    path?: never;
    query?: never;
    url: '/api/v1/forecasts/designated-day';
};

export type ForecastApiV1ForecastsDesignatedDayPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ForecastApiV1ForecastsDesignatedDayPostError = ForecastApiV1ForecastsDesignatedDayPostErrors[keyof ForecastApiV1ForecastsDesignatedDayPostErrors];

export type ForecastApiV1ForecastsDesignatedDayPostResponses = {
    /**
     * Successful Response
     */
    200: ForecastResponse;
};

export type ForecastApiV1ForecastsDesignatedDayPostResponse = ForecastApiV1ForecastsDesignatedDayPostResponses[keyof ForecastApiV1ForecastsDesignatedDayPostResponses];

export type GovernanceStatusApiV1GovernanceStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/governance/status';
};

export type GovernanceStatusApiV1GovernanceStatusGetResponses = {
    /**
     * Successful Response
     */
    200: GovernanceStatus;
};

export type GovernanceStatusApiV1GovernanceStatusGetResponse = GovernanceStatusApiV1GovernanceStatusGetResponses[keyof GovernanceStatusApiV1GovernanceStatusGetResponses];

export type QueryApiV1QueriesPostData = {
    body: QueryRequest;
    path?: never;
    query?: never;
    url: '/api/v1/queries';
};

export type QueryApiV1QueriesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QueryApiV1QueriesPostError = QueryApiV1QueriesPostErrors[keyof QueryApiV1QueriesPostErrors];

export type QueryApiV1QueriesPostResponses = {
    /**
     * Successful Response
     */
    200: QueryResponse;
};

export type QueryApiV1QueriesPostResponse = QueryApiV1QueriesPostResponses[keyof QueryApiV1QueriesPostResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];
