// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AssistantMessageRequest
 */
export type AssistantMessageRequest = {
    /**
     * Message
     */
    message: string;
};

/**
 * AssistantResponse
 */
export type AssistantResponse = {
    /**
     * Answer
     */
    answer: string;
    /**
     * Assumptions
     */
    assumptions?: Array<string>;
    /**
     * Charts
     */
    charts?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Evidence Refs
     */
    evidence_refs?: Array<string>;
    /**
     * Follow Up Questions
     */
    follow_up_questions?: Array<string>;
    /**
     * Key Findings
     */
    key_findings?: Array<string>;
    /**
     * Limitations
     */
    limitations?: Array<string>;
    /**
     * Recommendations
     */
    recommendations?: Array<string>;
};

/**
 * AuditSummary
 */
export type AuditSummary = {
    /**
     * Audit Id
     */
    audit_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Data Source
     */
    data_source: string;
    /**
     * Operation
     */
    operation: string;
    /**
     * Query Fingerprint
     */
    query_fingerprint: string;
    /**
     * Row Count
     */
    row_count: number;
    /**
     * Status
     */
    status: string;
};

/**
 * CatalogOption
 */
export type CatalogOption = {
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
};

/**
 * CatalogResponse
 */
export type CatalogResponse = {
    /**
     * Available Dates
     */
    available_dates: Array<string>;
    /**
     * Data Scope
     */
    data_scope: 'synthetic';
    default_time_range: TimeRange;
    /**
     * Dimensions
     */
    dimensions: Array<CatalogOption>;
    /**
     * Directions
     */
    directions: Array<CatalogOption>;
    /**
     * Lines
     */
    lines: Array<string>;
    /**
     * Metrics
     */
    metrics: Array<MetricCatalogItem>;
    /**
     * Stations
     */
    stations: Array<string>;
    /**
     * Timezone
     */
    timezone: 'Asia/Shanghai';
};

/**
 * DatasetEligibility
 */
export type DatasetEligibility = {
    /**
     * Eligible
     */
    eligible?: boolean;
    /**
     * Reasons
     */
    reasons?: Array<string>;
    /**
     * Requires Human Confirmation
     */
    requires_human_confirmation?: boolean;
};

/**
 * EntitySet
 */
export type EntitySet = {
    /**
     * Directions
     */
    directions?: Array<string>;
    /**
     * Groups
     */
    groups?: Array<string>;
    /**
     * Lines
     */
    lines?: Array<string>;
    /**
     * Regions
     */
    regions?: Array<string>;
    /**
     * Stations
     */
    stations?: Array<string>;
};

/**
 * EventSpec
 */
export type EventSpec = {
    /**
     * Attendance
     */
    attendance?: number;
    /**
     * Event Name
     */
    event_name?: string;
    /**
     * Impacted Stations
     */
    impacted_stations?: Array<string>;
    /**
     * Target Date
     */
    target_date?: string | null;
    /**
     * Venue
     */
    venue?: string | null;
};

/**
 * EvidenceItem
 */
export type EvidenceItem = {
    /**
     * Claim
     */
    claim: string;
    /**
     * Evidence Id
     */
    evidence_id: string;
    /**
     * Kind
     */
    kind: 'fact' | 'statistic' | 'chart' | 'model_output' | 'knowledge';
    /**
     * Step Id
     */
    step_id: string;
    /**
     * Value
     */
    value?: unknown;
};

/**
 * EvidencePacket
 */
export type EvidencePacket = {
    /**
     * Charts
     */
    charts?: Array<EvidenceItem>;
    /**
     * Conflicts
     */
    conflicts?: Array<string>;
    /**
     * Facts
     */
    facts?: Array<EvidenceItem>;
    /**
     * Knowledge Sources
     */
    knowledge_sources?: Array<EvidenceItem>;
    /**
     * Missing Evidence
     */
    missing_evidence?: Array<string>;
    /**
     * Model Outputs
     */
    model_outputs?: Array<EvidenceItem>;
    /**
     * Question
     */
    question: string;
    /**
     * Statistics
     */
    statistics?: Array<EvidenceItem>;
};

/**
 * ForecastRequest
 */
export type ForecastRequest = {
    /**
     * Limit
     */
    limit?: number;
    /**
     * Reference Date
     */
    reference_date: string;
    /**
     * Scheme Id
     */
    scheme_id: number;
    /**
     * Target Date
     */
    target_date: string;
};

/**
 * ForecastResponse
 */
export type ForecastResponse = {
    audit: AuditSummary;
    /**
     * Method
     */
    method: 'reference_day_copy';
    /**
     * Reference Date
     */
    reference_date: string;
    /**
     * Row Count
     */
    row_count: number;
    /**
     * Rows
     */
    rows: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Scheme Id
     */
    scheme_id: number;
    /**
     * Status
     */
    status: 'answer';
    /**
     * Target Date
     */
    target_date: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Data Scope
     */
    data_scope: 'synthetic';
    /**
     * Environment
     */
    environment: string;
    /**
     * Service
     */
    service: string;
    /**
     * Status
     */
    status: 'ok';
    /**
     * Version
     */
    version: string;
};

/**
 * HumanFeedback
 */
export type HumanFeedback = {
    /**
     * Accepted
     */
    accepted?: boolean | null;
    /**
     * Correction
     */
    correction: string;
    /**
     * Recorded At
     */
    recorded_at?: string;
};

/**
 * HumanFeedbackRequest
 */
export type HumanFeedbackRequest = {
    /**
     * Accepted
     */
    accepted: boolean;
    adopted_response?: AssistantResponse | null;
    /**
     * Correction
     */
    correction: string;
};

/**
 * IntentEnvelope
 */
export type IntentEnvelope = {
    /**
     * Ambiguities
     */
    ambiguities?: Array<string>;
    entities?: EntitySet;
    event_spec?: EventSpec | null;
    /**
     * Metrics
     */
    metrics?: Array<string>;
    /**
     * Needs Clarification
     */
    needs_clarification?: boolean;
    /**
     * Task Type
     */
    task_type: 'query' | 'compare' | 'forecast' | 'alert' | 'transfer' | 'geo' | 'correlation' | 'diagnosis' | 'trend' | 'report';
    /**
     * Time Scope
     */
    time_scope?: {
        [key: string]: unknown;
    };
    transfer_spec?: TransferAnalysisSpec | null;
    /**
     * User Goal
     */
    user_goal: string;
};

/**
 * MetricCatalogItem
 */
export type MetricCatalogItem = {
    /**
     * Dimensions
     */
    dimensions: Array<string>;
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Unit
     */
    unit: string;
};

/**
 * QueryFilter
 */
export type QueryFilter = {
    /**
     * Field
     */
    field: 'line_id' | 'station_id' | 'direction';
    /**
     * Operator
     */
    operator: 'eq' | 'in';
    /**
     * Value
     */
    value: string | Array<string>;
};

/**
 * QueryRequest
 */
export type QueryRequest = {
    /**
     * Dimensions
     */
    dimensions: Array<'line' | 'station' | 'direction' | 'time'>;
    /**
     * Filters
     */
    filters: Array<QueryFilter>;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Metric
     */
    metric: string;
    time_range: TimeRange;
};

/**
 * QueryResponse
 */
export type QueryResponse = {
    audit: AuditSummary;
    /**
     * Dimensions
     */
    dimensions: Array<string>;
    /**
     * Metric
     */
    metric: string;
    /**
     * Row Count
     */
    row_count: number;
    /**
     * Rows
     */
    rows: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Status
     */
    status: 'answer';
};

/**
 * RunRecord
 */
export type RunRecord = {
    adopted_response?: AssistantResponse | null;
    /**
     * Created At
     */
    created_at?: string;
    dataset_eligibility?: DatasetEligibility;
    /**
     * Events
     */
    events?: Array<{
        [key: string]: unknown;
    }>;
    evidence?: EvidencePacket | null;
    /**
     * Human Feedback
     */
    human_feedback?: Array<HumanFeedback>;
    intent?: IntentEnvelope | null;
    /**
     * Original Question
     */
    original_question: string;
    plan?: TaskPlan | null;
    /**
     * Provider
     */
    provider: string;
    /**
     * Replans
     */
    replans?: Array<TaskPlan>;
    response?: AssistantResponse | null;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Selected Context
     */
    selected_context?: {
        [key: string]: unknown;
    };
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Status
     */
    status?: 'running' | 'completed' | 'needs_clarification' | 'failed';
    /**
     * Tool Results
     */
    tool_results?: Array<ToolResult>;
    verification?: VerificationReport | null;
};

/**
 * SessionRecord
 */
export type SessionRecord = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Messages
     */
    messages?: Array<{
        [key: string]: string;
    }>;
    /**
     * Session Id
     */
    session_id: string;
};

/**
 * TaskPlan
 */
export type TaskPlan = {
    /**
     * Answer Format
     */
    answer_format?: string;
    /**
     * Expected Evidence
     */
    expected_evidence?: Array<string>;
    /**
     * Plan Id
     */
    plan_id: string;
    /**
     * Steps
     */
    steps: Array<ToolStep>;
    /**
     * Task Type
     */
    task_type: 'query' | 'compare' | 'forecast' | 'alert' | 'transfer' | 'geo' | 'correlation' | 'diagnosis' | 'trend' | 'report';
};

/**
 * TimeRange
 */
export type TimeRange = {
    /**
     * End
     */
    end: string;
    /**
     * Start
     */
    start: string;
};

/**
 * ToolResult
 */
export type ToolResult = {
    /**
     * Artifact Refs
     */
    artifact_refs?: Array<string>;
    /**
     * Error Code
     */
    error_code?: string | null;
    /**
     * Rows
     */
    rows?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Status
     */
    status: 'success' | 'failed' | 'skipped';
    /**
     * Step Id
     */
    step_id: string;
    /**
     * Summary
     */
    summary?: {
        [key: string]: unknown;
    };
    /**
     * Tool
     */
    tool: string;
    /**
     * Warnings
     */
    warnings?: Array<string>;
};

/**
 * ToolStep
 */
export type ToolStep = {
    /**
     * Arguments
     */
    arguments?: {
        [key: string]: unknown;
    };
    /**
     * Depends On
     */
    depends_on?: Array<string>;
    /**
     * Step Id
     */
    step_id: string;
    /**
     * Tool
     */
    tool: string;
};

/**
 * TransferAnalysisSpec
 */
export type TransferAnalysisSpec = {
    /**
     * Bus Scope
     */
    bus_scope?: Array<string>;
    /**
     * Output Dimensions
     */
    output_dimensions?: Array<string>;
    /**
     * Rail Scope
     */
    rail_scope?: Array<string>;
    /**
     * Window Minutes
     */
    window_minutes?: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VerificationReport
 */
export type VerificationReport = {
    /**
     * Errors
     */
    errors?: Array<string>;
    /**
     * Supported Evidence Refs
     */
    supported_evidence_refs?: Array<string>;
    /**
     * Valid
     */
    valid: boolean;
    /**
     * Warnings
     */
    warnings?: Array<string>;
};

export type AssistantRunApiV1AssistantRunsRunIdGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/assistant/runs/{run_id}';
};

export type AssistantRunApiV1AssistantRunsRunIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssistantRunApiV1AssistantRunsRunIdGetError = AssistantRunApiV1AssistantRunsRunIdGetErrors[keyof AssistantRunApiV1AssistantRunsRunIdGetErrors];

export type AssistantRunApiV1AssistantRunsRunIdGetResponses = {
    /**
     * Successful Response
     */
    200: RunRecord;
};

export type AssistantRunApiV1AssistantRunsRunIdGetResponse = AssistantRunApiV1AssistantRunsRunIdGetResponses[keyof AssistantRunApiV1AssistantRunsRunIdGetResponses];

export type AssistantEventsApiV1AssistantRunsRunIdEventsGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/assistant/runs/{run_id}/events';
};

export type AssistantEventsApiV1AssistantRunsRunIdEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssistantEventsApiV1AssistantRunsRunIdEventsGetError = AssistantEventsApiV1AssistantRunsRunIdEventsGetErrors[keyof AssistantEventsApiV1AssistantRunsRunIdEventsGetErrors];

export type AssistantEventsApiV1AssistantRunsRunIdEventsGetResponses = {
    /**
     * Response Assistant Events Api V1 Assistant Runs  Run Id  Events Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type AssistantEventsApiV1AssistantRunsRunIdEventsGetResponse = AssistantEventsApiV1AssistantRunsRunIdEventsGetResponses[keyof AssistantEventsApiV1AssistantRunsRunIdEventsGetResponses];

export type AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostData = {
    body: HumanFeedbackRequest;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/assistant/runs/{run_id}/feedback';
};

export type AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostError = AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostErrors[keyof AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostErrors];

export type AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostResponses = {
    /**
     * Successful Response
     */
    200: RunRecord;
};

export type AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostResponse = AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostResponses[keyof AssistantFeedbackApiV1AssistantRunsRunIdFeedbackPostResponses];

export type CreateAssistantSessionApiV1AssistantSessionsPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/assistant/sessions';
};

export type CreateAssistantSessionApiV1AssistantSessionsPostResponses = {
    /**
     * Successful Response
     */
    200: SessionRecord;
};

export type CreateAssistantSessionApiV1AssistantSessionsPostResponse = CreateAssistantSessionApiV1AssistantSessionsPostResponses[keyof CreateAssistantSessionApiV1AssistantSessionsPostResponses];

export type AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostData = {
    body: AssistantMessageRequest;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/assistant/sessions/{session_id}/messages';
};

export type AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostError = AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostErrors[keyof AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostErrors];

export type AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostResponses = {
    /**
     * Successful Response
     */
    200: RunRecord;
};

export type AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostResponse = AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostResponses[keyof AssistantMessageApiV1AssistantSessionsSessionIdMessagesPostResponses];

export type AuditApiV1AuditsAuditIdGetData = {
    body?: never;
    path: {
        /**
         * Audit Id
         */
        audit_id: string;
    };
    query?: never;
    url: '/api/v1/audits/{audit_id}';
};

export type AuditApiV1AuditsAuditIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuditApiV1AuditsAuditIdGetError = AuditApiV1AuditsAuditIdGetErrors[keyof AuditApiV1AuditsAuditIdGetErrors];

export type AuditApiV1AuditsAuditIdGetResponses = {
    /**
     * Successful Response
     */
    200: AuditSummary;
};

export type AuditApiV1AuditsAuditIdGetResponse = AuditApiV1AuditsAuditIdGetResponses[keyof AuditApiV1AuditsAuditIdGetResponses];

export type CatalogApiV1CatalogGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/catalog';
};

export type CatalogApiV1CatalogGetResponses = {
    /**
     * Successful Response
     */
    200: CatalogResponse;
};

export type CatalogApiV1CatalogGetResponse = CatalogApiV1CatalogGetResponses[keyof CatalogApiV1CatalogGetResponses];

export type ForecastApiV1ForecastsDesignatedDayPostData = {
    body: ForecastRequest;
    path?: never;
    query?: never;
    url: '/api/v1/forecasts/designated-day';
};

export type ForecastApiV1ForecastsDesignatedDayPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ForecastApiV1ForecastsDesignatedDayPostError = ForecastApiV1ForecastsDesignatedDayPostErrors[keyof ForecastApiV1ForecastsDesignatedDayPostErrors];

export type ForecastApiV1ForecastsDesignatedDayPostResponses = {
    /**
     * Successful Response
     */
    200: ForecastResponse;
};

export type ForecastApiV1ForecastsDesignatedDayPostResponse = ForecastApiV1ForecastsDesignatedDayPostResponses[keyof ForecastApiV1ForecastsDesignatedDayPostResponses];

export type QueryApiV1QueriesPostData = {
    body: QueryRequest;
    path?: never;
    query?: never;
    url: '/api/v1/queries';
};

export type QueryApiV1QueriesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QueryApiV1QueriesPostError = QueryApiV1QueriesPostErrors[keyof QueryApiV1QueriesPostErrors];

export type QueryApiV1QueriesPostResponses = {
    /**
     * Successful Response
     */
    200: QueryResponse;
};

export type QueryApiV1QueriesPostResponse = QueryApiV1QueriesPostResponses[keyof QueryApiV1QueriesPostResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];
